# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool: Local_AT

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  solution: '**/*.sln'
  project: '**/*.csproj'

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'kv-service-connection'
    KeyVaultName: 'rest-api-kv'
    SecretsFilter: '*'
    RunAsPreJob: true
    
- task: NuGetToolInstaller@1
  inputs:
      restoreSolution: '$(solution)'
  #name: 'NuGetToolInstaller'
  displayName: 'NuGet tool installer'
  
- task: NuGetCommand@2
  name: 'NuGetRestore'
  displayName: 'NuGet restore packages'
  inputs:
   command: 'restore'
   restoreSolution: '$(solution)'
   feedsToUse: 'select'

- task: DotNetCoreCLI@2
  name: 'Tests'
  displayName: 'Run tests'
  inputs:
    command: 'test'
    projects: '$(solution)'
    arguments: '--configuration $(BuildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)/publish'
    artifactName: 'drop'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'kv-service-connection'
    appType: 'webApp'
    appName: 'toht-web-app'
    package: '' #$(build.artifactStagingDirectory)/publish/*.zip
    deploymentMethod: 'auto'
